### PR TITLE
Supports for-in loop inside block

### PR DESCRIPTION
**Pull request by muukii**
https://github.com/FluidGroup/MondrianLayout/issues/76

### CODE REVIEW

**Comment by BayramInanc** [comment]
yes, it did work. Thank you

**Comment by BayramInanc** [comment]
can we make it also HStack?

**Comment by BayramInanc** [comment]
and Z :)

**Comment by muukii** [comment]
yup I think it works in there, doesn't it?

**Comment by muukii** [comment]
oh I did mistake. it needs a bit more. will do. thanks

**Comment by muukii** [comment]
ok it's done

**Comment by BayramInanc** [comment]
thank you so much

**Pull request merged**
